# -*- coding: utf-8 -*-
"""video 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOgqEQvZBenGUG5tgOV4IzBiJWbfc2zZ
"""

import pandas as pd

datos = pd.read_csv("Customer.csv")

datos.shape

datos.head()